# Generated by Django 3.0.2 on 2020-01-09 19:27

from django.db import migrations, models
import django.db.models.deletion
import uzprotect_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.TextField(verbose_name='Наша деятельность')),
            ],
            options={
                'verbose_name': 'Наша деятельность',
                'verbose_name_plural': 'Наши деятельности',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название сферы деятельности')),
                ('slug', models.SlugField(verbose_name='Альтернативное название')),
            ],
            options={
                'verbose_name': 'Сфера деятельность',
                'verbose_name_plural': 'Сфера деятельности',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название продукта')),
                ('slug', models.SlugField(verbose_name='Альтернативное название')),
                ('description', models.TextField(verbose_name='Описание продукта')),
                ('price', models.PositiveIntegerField(verbose_name='Цена продукта')),
                ('image', models.ImageField(upload_to=uzprotect_app.models.image_folder, verbose_name='Картинка продукта')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uzprotect_app.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
