# Generated by Django 3.0.2 on 2020-01-09 20:10

from django.db import migrations, models
import uzprotect_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('uzprotect_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(upload_to=uzprotect_app.models.image_folder, verbose_name='Фоновое Изображение')),
                ('title', models.CharField(default='UZPROTECT', max_length=200, verbose_name='Название компании')),
            ],
            options={
                'verbose_name': 'Фоновое изображение',
                'verbose_name_plural': 'Фоновое изображение',
            },
        ),
    ]
