# Generated by Django 3.0.2 on 2020-01-09 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uzprotect_app', '0002_backgroundimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackgroundImage',
        ),
    ]
